encoding: "utf-8"

include:
  - "*.md"
  - "*.cpp"
  - "**/*.md"
  - "**/*.cpp"

collections:
  all_files:
    output: true
    permalink: /:path/:basename  # 保持原始URL路径
    
include:
  - _includes/head-custom.html